import sqlite3
conn = sqlite3.connect('plm_dashboard.db')
cur = conn.cursor()
cur.execute("DELETE FROM scrape_history WHERE data_type='part'")
conn.commit()
print('deleted:', cur.rowcount)
cur.execute("SELECT COUNT(*) FROM scrape_history WHERE data_type='part'")
print('remaining:', cur.fetchone()[0])
cur.execute("DELETE FROM scrape_current WHERE data_type='part'")
conn.commit()
print('current deleted:', cur.rowcount)
