import sqlite3
conn = sqlite3.connect('plm_dashboard.db')
conn.execute('VACUUM')
cur = conn.cursor()
cur.execute("SELECT COUNT(*) FROM scrape_history WHERE data_type='part'")
print('history count:', cur.fetchone()[0])
cur.execute("SELECT COUNT(*) FROM scrape_current WHERE data_type='part'")
print('current count:', cur.fetchone()[0])
cur.execute('SELECT COUNT(*) FROM scrape_history')
print('total history:', cur.fetchone()[0])
cur.execute('SELECT COUNT(*) FROM scrape_current')
print('total current:', cur.fetchone()[0])
conn.close()
print('VACUUM done')
